### ISSUE TITLE
最新版是抛弃老版么,老版设置都失效,全部通过自定义的tabbarView去实现功能了?

### ISSUE THREAD

**Issue by SongLog** [EFPrefix/EFNavigationBar#5]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [x] I have read the [README.md](https://github.com/EFPrefix/EFNavigationBar/blob/master/README.md), but there is no information I need.
- [x] I have searched in [existing issues](https://github.com/EFPrefix/EFNavigationBar/issues?utf8=%E2%9C%93&q=is%3Aissue), but did find a same one.

#### Description

[Tell us about the issue]

#### Reproduce

[The steps to reproduce this issue. What are the parameters, where did you put your code, etc.]

#### Other Comment

[Add anything else here]

**Comment by EyreFree** [comment]
没错，之后会全部依赖自定义导航栏来实现。
