### ISSUE TITLE
支持OC吗 现在原来oc版本已经在项目里面根深蒂固了, iOS13上面有比较多的问题, 没办法解决. 这个要是支持OC我就想办法移植过去

### ISSUE THREAD

**Issue by Miles-Matheson** [EFPrefix/EFNavigationBar#8]
### Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [ ] I have read the [README.md](https://github.com/EFPrefix/EFNavigationBar/blob/master/README.md), but there is no information I need.
- [ ] I have searched in [existing issues](https://github.com/EFPrefix/EFNavigationBar/issues?utf8=%E2%9C%93&q=is%3Aissue), but did find a same one.

#### Description

[Tell us about the issue]

#### Reproduce

[The steps to reproduce this issue. What are the parameters, where did you put your code, etc.]

#### Other Comment

[Add anything else here]

**Comment by EyreFree** [comment]
@Miles-Matheson 

不支持 OC 的，抱歉，而且目前本项目已经和 [WRNavigationBar](https://github.com/wangrui460/WRNavigationBar) 并不完全对等了，针对您的情况还是建议 fork 并修改之前的 OC 版本。
